# ================================
# Parameter Definition File
# ================================

# ===============================
# Project Title
# ===============================
project_title: "GMC_Banavati_CaCx_sim"

# ===============================
# Simulation Parameters
# ===============================
simulation:
  name: "GMC_Banavati_CaCx_sim"
  run_time: 1000 # in days = 3 years approx
  experiment_no: 1
  no_of_sims: 50
  working_days: 25 # per month
  working_hours: 3 # Decision on whether to use as an output or an input parameter?

  # ===============================
  # Hospital Parameters
  # ===============================
  #Workload
  #Cytology
  pap_per_day: 5
  non_pap_per_day: 20
  #Histology
  cervical_biopsies_per_day: 2
  non_cervical_biopsies_per_day: 5
  proportion_of_cervical_samples: 0.286 # default ~2/(2+5)

# ==============================
# Resources
# ==============================
Staff:
  #Cytology
  num_cytopathologists: 3
  num_cytotechnicians: 2
  #Histology
  num_histopathologists: 6
  num_histotechnicians: 8 (11)

Infrastructure:
  num_cyto_staining_stations: 1 #manual staining station
  num_cyto_microscopes: 3
  #Histology
  num_grossing_stations: 2
  num_tissue_processors: 1 #tissue processor that does dehydration, clearing and infiltration
  num_embedding_stations: 1 #embed tissue in paraffin wax
  num_sectioning_stations: 2 #microtome to cut thin sections of tissue
  num_histo_staining_stations: 1  #autostainer #Multiple other stations for manual staining
  num_histo_microscopes: 3

Consumables: # This is very challenging to estimate 900 ml Slides in 500 ml reagent. for hematoxylin
  pap_stain_reagents_per_slide: 0.5 #ml
  giemsa_stain_reagents_per_slide: 0.5 #ml
  h&e_stain_reagents_per_slide: 0.5 #ml
  fixation_reagents_per_slide: 0.5 #ml

Consumable Shelf: # Need to take gross averages. 500 ml 900 slides. 
  hematoxylin_shelf_life: 14 # days (7-10 days)
  eosin_shelf_life: 14 # days
  giemsa_shelf_life: 14 # days
  OG6_shelf_life: 14 # days
  alcohol_shelf_life: 2 # days
  xylene_shelf_life: 2 # days
  paraffin_shelf_life: 15 # days
  xylene_processing_shelf_life: 7 # days depends on number of blocks processed

Batch Sizes:
  cyto_staining_station_batch_size: 10 # slides per batch for staining
  #Histology
  grossing_batch_size: 20 # samples per batch grossing
  tissue_processor_batch_size: 90 # blocks per batch for tissue processing (1 sample can have multiple blocks) - 1 block = 1 slide
  embedding_batch_size: 1 # samples per batch for embedding
  sectioning_batch_size: 1 # samples per batch for sectioning
  histo_staining_batch_size: 25-30 # slides per batch for staining (autostainer)

# ==============================
# Service Times
# ==============================
#Cytology
processing:
  cyto_slides: 60 # minutes per slide # Constant time

fixation:
  small_biopsy: 60 # minutes
  medium_biopsy: 90 # minutes
  large_biopsy: 120 # minutes
reporting:
  cyto_slides: 30 # minutes per slide # Distribution Estimated by a bayesian distribution
  cyto_slide_distribution:
    type: "lognormal"
    mean: 3.4
    sd: 0.4
  histo_samples: 120 # minutes per slide # Distribution Estimated by a bayesian distribution
  histo_sample_distribution:
    type: "lognormal"
    mean: 4.8
    sd: 0.5

#Histology
grossing:
  small_biopsy: 30 # minutes per sample # Constant time
  medium_biopsy: 60 # minutes per sample # Constant time 
  large_biopsy: 90 # minutes per sample # Constant time
fixation:
  small_biopsy: 6 # minutes 6 hours
  medium_biopsy: 90 # minutes 
  large_biopsy: 120 # minutes 72 hours
tissue_processing:
  tissue_processor_batch_time: 22 hours # minutes per batch for tissue processing (1 batch = 90 blocks) # Constant time - Follow a standard textbooks?
embedding:
  embedding_time: 30 seconds - 1 minute # minutes per sample # Constant time
 
sectioning:
  cervical_biopsy: 30 secs - 1 minute # minutes per block # Constant time
  non_cervical_biopsy: 30 # minutes per sample # Constant time

# ==============================
# Epidemiological parameters
# ==============================
pap_positive_rate: 0.05
cervical_biopsy_positive_rate: 0.15
cin_prevalence_rate: 0.10
cervical_cancer_prevalence_rate: 0.02
# ==============================
# END
# ==============================

# ==============================
# Histology Parameters
# ==============================

