#import libraries

import simpy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import random
import os
import yaml

#Import parameters from YAML File
def import_parameters(file_path = "parameters.yaml"):
    with open(file_path, 'r') as file:
        parameters = yaml.safe_load(file)
    return parameters
# ================================


#Defining the Slide Class
class CytoSlide:
    """
    A cytology slide generated by a patient sample.
    """
    def __init__(self, id, is_pap = False, is_positive = False, arrival_time = None):
        self.id = id
        
        # Slide type
        self.is_pap = is_pap
        self.is_positive = is_positive if is_pap else None # Only pap slides can be positive
        
        # Timestamps
        self.arrival_time = arrival_time
        self.start_processing_time = None
        self.start_reporting_time = None
        self.exit_time = None
        
class HistoSample:
    """
    A histology sample generated by a patient biopsy.
    """
    def __init__(self, id, size = 'small', is_positive = False, arrival_time = None):
        self.id = id
        
        # Slide Types
        self.size = size  # small, medium, large
        self.is_positive = is_positive
       
       # Timestamps
        self.arrival_time = arrival_time
        self.start_processing_time = None
        self.start_reporting_time = None
        self.exit_time = None

# ================================
# Utility Functions
# ================================

def is_working_hours(env):
    """
    Check if current simulation time is within working hours:
    Monday to Saturday, 9 AM to 4 PM
    """
    # Get current day and time
    current_day = int(env.now) % 7  # 0 = Monday, 6 = Sunday
    current_hour = (env.now % 1) * 24  # Hour of the day (0-24)
    
    # Check if it's Monday to Saturday (0-5)
    is_working_day = current_day < 6
    
    # Check if it's between 9 AM and 4 PM
    is_working_time = 9 <= current_hour < 16
    
    return is_working_day and is_working_time

def get_next_working_time(env):
    """
    Calculate the next working time if current time is outside working hours
    """
    current_day = int(env.now) % 7
    current_hour = (env.now % 1) * 24
    
    # If it's Sunday (day 6), wait until Monday 9 AM
    if current_day == 6:
        hours_until_monday_9am = (24 - current_hour) + 9
        return hours_until_monday_9am / 24
    
    # If it's after 4 PM, wait until next day 9 AM
    if current_hour >= 16:
        hours_until_next_9am = (24 - current_hour) + 9
        return hours_until_next_9am / 24
    
    # If it's before 9 AM, wait until 9 AM today
    if current_hour < 9:
        return (9 - current_hour) / 24
    
    return 0

# ================================
# Simulation Processes
# ================================

def cyto_sample_generator(env, params, cyto_processing_queue):
    """
    Generate cytology samples and add them to the processing queue.
    Samples arrive only during working hours (Mon-Sat, 9 AM - 4 PM).
    """
    slide_id = 1
    
    while True:
        # Check if we're in working hours
        if not is_working_hours(env):
            # Wait until next working time
            wait_time = get_next_working_time(env)
            yield env.timeout(wait_time)
            continue
        
        # Generate Pap slides
        for _ in range(params['simulation']['pap_per_day']):
            is_positive = random.random() < params['pap_positive_rate']
            slide = CytoSlide(
                id=slide_id,
                is_pap=True,
                is_positive=is_positive,
                arrival_time=env.now
            )
            cyto_processing_queue.append(slide)
            print(f"[{env.now:.2f}] Pap slide {slide_id} arrived (Positive: {is_positive})")
            slide_id += 1
        
        # Generate Non-Pap slides
        for _ in range(params['simulation']['non_pap_per_day']):
            slide = CytoSlide(
                id=slide_id,
                is_pap=False,
                arrival_time=env.now
            )
            cyto_processing_queue.append(slide)
            print(f"[{env.now:.2f}] Non-Pap slide {slide_id} arrived")
            slide_id += 1
        
        # Wait for the rest of the day (spread arrivals throughout the day)
        # Arrivals happen once per day
        yield env.timeout(1)  # 1 day


def decision_to_process_slide(slide, params):
    """
    Decide whether to process a slide based on its type and parameters.
    For simplicity, we assume all slides are processed in this simulation.
    """
    return True



def cyto_sample_processor(env, params, cyto_processing_queue, cyto_reporting_queue, cytotechnicians):
    """
    Process cytology slides from the processing queue.
    Requires a cytotechnician resource.
    """
    while True:
        if len(cyto_processing_queue) > 0:
            slide = cyto_processing_queue.pop(0)
            
            # Request a cytotechnician
            with cytotechnicians.request() as request:
                yield request
                
                slide.start_processing_time = env.now
                print(f"[{env.now:.2f}] Started processing slide {slide.id}")
                
                # Processing time (convert minutes to days)
                processing_time = params['processing']['cyto_slides'] / (60 * 24)
                yield env.timeout(processing_time)
                
                # Move to reporting queue
                cyto_reporting_queue.append(slide)
                print(f"[{env.now:.2f}] Finished processing slide {slide.id}, moved to reporting")
        else:
            # Wait a bit before checking again
            yield env.timeout(0.01)

def cyto_sample_reporter(env, params, cyto_reporting_queue, cytopathologists, results):
    """
    Report on cytology slides from the reporting queue.
    Requires a cytopathologist resource.
    """
    while True:
        if len(cyto_reporting_queue) > 0:
            slide = cyto_reporting_queue.pop(0)
            
            # Request a cytopathologist
            with cytopathologists.request() as request:
                yield request
                
                slide.start_reporting_time = env.now
                print(f"[{env.now:.2f}] Started reporting slide {slide.id}")
                
                # Reporting time - using lognormal distribution
                mean = params['reporting']['cyto_slide_distribution']['mean']
                sd = params['reporting']['cyto_slide_distribution']['sd']
                reporting_minutes = np.random.lognormal(mean, sd)
                reporting_time = reporting_minutes / (60 * 24)  # Convert to days
                
                yield env.timeout(reporting_time)
                
                slide.exit_time = env.now
                
                # Calculate turnaround time
                turnaround_time = slide.exit_time - slide.arrival_time
                
                # Store results
                results.append({
                    'slide_id': slide.id,
                    'slide_type': 'Pap' if slide.is_pap else 'Non-Pap',
                    'is_positive': slide.is_positive,
                    'arrival_time': slide.arrival_time,
                    'start_processing_time': slide.start_processing_time,
                    'start_reporting_time': slide.start_reporting_time,
                    'exit_time': slide.exit_time,
                    'turnaround_time': turnaround_time
                })
                
                print(f"[{env.now:.2f}] Finished reporting slide {slide.id} (TAT: {turnaround_time:.2f} days)")
        else:
            # Wait a bit before checking again
            yield env.timeout(0.01)

# ================================
# Main Simulation
# ================================

def run_simulation(params):
    """
    Run the cytology department simulation.
    """
    # Create SimPy environment
    env = simpy.Environment()
    
    # Create resources
    cytotechnicians = simpy.Resource(env, capacity=params['Staff']['num_cytotechnicians'])
    cytopathologists = simpy.Resource(env, capacity=params['Staff']['num_cytopathologists'])
    
    # Create queues
    cyto_processing_queue = []
    cyto_reporting_queue = []
    
    # Results storage
    results = []
    
    # Start processes
    env.process(cyto_sample_generator(env, params, cyto_processing_queue))
    env.process(cyto_sample_processor(env, params, cyto_processing_queue, cyto_reporting_queue, cytotechnicians))
    env.process(cyto_sample_reporter(env, params, cyto_reporting_queue, cytopathologists, results))
    
    # Run simulation
    run_time = params['simulation']['run_time']
    print(f"\n{'='*60}")
    print(f"Starting Cytology Department Simulation")
    print(f"Run time: {run_time} days")
    print(f"{'='*60}\n")
    
    env.run(until=run_time)
    
    print(f"\n{'='*60}")
    print(f"Simulation Complete")
    print(f"Total slides processed: {len(results)}")
    print(f"{'='*60}\n")
    
    # Convert results to DataFrame
    df_results = pd.DataFrame(results)
    
    if len(results) > 0:
        print("\nSummary Statistics:")
        print(f"Average Turnaround Time: {df_results['turnaround_time'].mean():.2f} days")
        print(f"Median Turnaround Time: {df_results['turnaround_time'].median():.2f} days")
        print(f"Min Turnaround Time: {df_results['turnaround_time'].min():.2f} days")
        print(f"Max Turnaround Time: {df_results['turnaround_time'].max():.2f} days")
    
    return df_results

# Run the simulation
if __name__ == "__main__":
    parameters = import_parameters("parameters.yaml")
    results_df = run_simulation(parameters)
    print(results_df)
    results_df.to_csv("cytology_simulation_results.csv", index=False)
    